name: pruebatabx
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com
# author: iblasco <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^5.0.0
  ng_bootstrap: 1.0.3

dev_dependencies:
  build_runner: ^1.1.1
  build_web_compilers: ^0.4.4+2
  test: ^1.0.0
